

spring:
  rabbitmq:
    host: www.sdemo.com
    port: 5672
    username: admin
    password: admin
    connection-timeout: 10000
    virtual-host: /
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
server:
  port: 2002


mq:
  fanout:
    exchange:
      test: lua-test-exchange
    queue:
      test: lua-test-queue

  direct:
    nginx:
      exchange: 'direct.nginx.exchange'
      queue: 'direct.nginx.delcache.queue'
      rounting: 'DirectNginxRouting'
      ip: 'http://10.2.9.63:80'