server:
  port: 2000

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 30
        min-idle: 10
        max-wait: 60s
      shutdown-timeout: 100
    # \u96C6\u7FA4\u914D\u7F6E
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#        - 127.0.0.1:6380
#        - 127.0.0.1:6381
#      max-redirects: 3